# Generated by GitHub Copilot
"""
Feature engineering for the ML win-rate prediction model.

Loads combo specs + performance data from the DB and returns (X, y) DataFrames
ready for scikit-learn.

Target: ``win_rate`` (regression)
Features:
  - Numeric: blade_weight_g, ratchet_weight_g, bit_weight_g, ratchet_gears, bit_height_mm
  - One-hot: blade_type, bit_type, blade_spin, ratchet_burst_resistance
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pandas as pd
from sqlalchemy import text

from app.database import SessionLocal

# Numeric feature columns sourced directly from the combos table
_NUMERIC_FEATURES = [
    "blade_weight_g",
    "ratchet_weight_g",
    "bit_weight_g",
    "ratchet_gears",
    "bit_height_mm",
]

# Categorical columns to one-hot encode
_CATEGORICAL_FEATURES = [
    "blade_type",
    "bit_type",
    "blade_spin",
    "ratchet_burst_resistance",
]


def load_features(season: str = "Season 2026") -> tuple[pd.DataFrame, pd.Series]:
    """
    Query the DB and return (X, y) for supervised training.

    Parameters
    ----------
    season : str
        Season to filter performance data on. Defaults to ``"Season 2026"``
        to avoid data leakage across seasons.

    Returns
    -------
    X : pd.DataFrame
        Encoded feature matrix with no NaN values.
    y : pd.Series
        Target vector (win_rate, float in [0, 1]).
    """
    db = SessionLocal()
    try:
        q = text("""
            SELECT
                c.blade_weight_g,
                c.ratchet_weight_g,
                c.bit_weight_g,
                c.ratchet_gears,
                c.bit_height_mm,
                c.blade_type,
                c.bit_type,
                c.blade_spin,
                c.ratchet_burst_resistance,
                cp.win_rate
            FROM combos c
            JOIN combo_performance cp ON cp.combo_key = c.combo_key
            WHERE cp.season = :season
              AND cp.win_rate IS NOT NULL
        """)
        df = pd.read_sql(q, db.bind, params={"season": season})
    finally:
        db.close()

    if df.empty:
        raise ValueError(f"No rows found for season '{season}'")

    # Separate target
    y = df["win_rate"].astype(float)
    df = df.drop(columns=["win_rate"])

    # One-hot encode categoricals (drop_first avoids perfect multicollinearity)
    df = pd.get_dummies(df, columns=_CATEGORICAL_FEATURES, drop_first=False, dtype=float)

    # Fill remaining numeric NaN with column median (imputation at training time)
    df = df.fillna(df.median(numeric_only=True))

    return df, y


def available_seasons() -> list[str]:
    """Return the list of distinct seasons stored in combo_performance."""
    db = SessionLocal()
    try:
        rows = db.execute(text("SELECT DISTINCT season FROM combo_performance ORDER BY season")).fetchall()
        return [r[0] for r in rows]
    finally:
        db.close()
