# Generated by GitHub Copilot
"""
Train a RandomForest regressor to predict combo win-rate from part specs.

Usage (from workspace root):
    python ml/train.py [--season "Season 2026"] [--output models/rf_winrate.joblib]

The trained model and feature column list are saved via joblib so they can be
loaded by the Streamlit ML Analysis page for inference.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import joblib
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

from ml.features import load_features

_DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / "models" / "rf_winrate.joblib"


def train(season: str = "Season 2026", output_path: Path = _DEFAULT_OUTPUT) -> dict:
    """
    Train a RandomForestRegressor on the given season's data.

    Parameters
    ----------
    season : str
        Season to train on.
    output_path : Path
        Destination .joblib file for the saved model bundle.

    Returns
    -------
    dict
        Evaluation metrics: ``rmse``, ``r2``, ``n_train``, ``n_test``.
    """
    X, y = load_features(season=season)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model = RandomForestRegressor(
        n_estimators=200,
        max_depth=None,
        min_samples_leaf=2,
        random_state=42,
        n_jobs=-1,
    )
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    rmse = float(np.sqrt(mean_squared_error(y_test, y_pred)))
    r2 = float(r2_score(y_test, y_pred))

    # Save model bundle: model + feature columns for consistent inference
    output_path.parent.mkdir(parents=True, exist_ok=True)
    bundle = {
        "model": model,
        "feature_columns": list(X.columns),
        "season": season,
    }
    joblib.dump(bundle, output_path)

    return {
        "rmse": rmse,
        "r2": r2,
        "n_train": len(X_train),
        "n_test": len(X_test),
        "output": str(output_path),
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train win-rate prediction model")
    parser.add_argument("--season", default="Season 2026", help="Season to train on")
    parser.add_argument("--output", default=str(_DEFAULT_OUTPUT), help="Output .joblib path")
    args = parser.parse_args()

    metrics = train(season=args.season, output_path=Path(args.output))

    print(f"\nModel trained on season: {metrics['season'] if 'season' in metrics else args.season}")
    print(f"  Train rows : {metrics['n_train']}")
    print(f"  Test rows  : {metrics['n_test']}")
    print(f"  RMSE       : {metrics['rmse']:.4f}")
    print(f"  R²         : {metrics['r2']:.4f}")
    print(f"  Saved to   : {metrics['output']}")
