"""
join_parts_meta.py
──────────────────
Joins beyblade_parts.csv specs into beyblade_meta_analytics.csv on part names,
producing beyblade_combined.csv — one enriched row per ranked combo per season.

Name normalisation strategies
──────────────────────────────
• blade       : remove spaces, lowercase  ("Wizard Rod" → "wizardrod")
• ratchet     : exact match               ("1-60" = "1-60")
• bit         : extract text inside "(…)", remove spaces, lowercase
                ("Lr (Low Rush)" → "lowrush")
• assist_blade: same extraction as bit    ("S (Slash)" → "slash")

Usage
──────
  python join_parts_meta.py
  python join_parts_meta.py --parts beyblade_parts.csv --meta beyblade_meta_analytics.csv --output beyblade_combined.csv
"""

# Generated by GitHub Copilot

import csv
import re
import argparse
import logging
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# ── Spec columns kept per part category ───────────────────────────────────────

BLADE_COLS = ["weight_g", "type", "spin", "contact_points"]
RATCHET_COLS = ["weight_g", "gears", "burst_resistance"]
BIT_COLS = ["weight_g", "type", "height_mm"]
ASSIST_COLS = ["weight_g", "type", "high_level_mm"]

_PARENS_RE = re.compile(r"\(([^)]+)\)")


# ── Manual aliases (meta name → normalised parts key) ─────────────────────────
# Applied when the automated normalisation alone doesn't produce a match.

BLADE_ALIASES: dict[str, str] = {
    # meta camelCase  : normalised key from parts name
    "hoverwyvern": "wyvernhover",   # parts: "Wyvern Hover"; meta: "HoverWyvern"
    "eclipse": "soleclipse",        # parts: "Sol Eclipse";   meta: "Eclipse"
}

# ── Key normalisation helpers ──────────────────────────────────────────────────

def _norm_blade(name: str) -> str:
    """Remove all spaces and lowercase — matches camelCase meta values."""
    raw = name.replace(" ", "").lower()
    return BLADE_ALIASES.get(raw, raw)


def _norm_ratchet(name: str) -> str:
    """Ratchets already share the same format; just lowercase for safety."""
    return name.strip().lower()


def _norm_paren(name: str) -> str:
    """Extract the word(s) inside the first parentheses, strip spaces, lowercase.

    Handles:
      "Lr (Low Rush)" → "lowrush"
      "S (Slash)"     → "slash"
    Falls back to the raw name normalised like a blade if no parens are found.
    """
    m = _PARENS_RE.search(name)
    if m:
        return m.group(1).replace(" ", "").lower()
    return _norm_blade(name)


# ── Lookup builder ─────────────────────────────────────────────────────────────

def build_lookups(parts_path: Path) -> dict[str, dict[str, dict]]:
    """
    Returns a dict of category → {normalised_key → part_row_dict}.

    Security: reads only local CSV; no external input interpolated into queries.
    """
    lookups: dict[str, dict[str, dict]] = {
        "blade": {},
        "ratchet": {},
        "bit": {},
        "assist-blade": {},
    }

    with parts_path.open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            cat = row["category"]
            if cat not in lookups:
                continue
            name = row["name"]
            if cat == "blade":
                key = _norm_blade(name)
            elif cat == "ratchet":
                key = _norm_ratchet(name)
            else:  # bit or assist-blade
                key = _norm_paren(name)
            lookups[cat][key] = row

    for cat, d in lookups.items():
        log.info("  %s lookup: %d entries", cat, len(d))

    return lookups


# ── Row enrichment ─────────────────────────────────────────────────────────────

def _prefix_cols(part_row: dict | None, columns: list[str], prefix: str) -> dict:
    """Build {prefix_col: value} dict from a (possibly missing) part row."""
    if part_row is None:
        return {f"{prefix}_{c}": "" for c in columns}
    return {f"{prefix}_{c}": part_row.get(c, "") for c in columns}


def enrich_row(
    meta_row: dict,
    lookups: dict[str, dict[str, dict]],
    unmatched: dict[str, set],
) -> dict:
    """Attach part specs to a single meta combo row."""
    blade_key = _norm_blade(meta_row["blade"])
    ratchet_key = _norm_ratchet(meta_row["ratchet"])
    bit_key = _norm_paren(meta_row["bit"])

    raw_assist = meta_row["assist_blade"]
    assist_key = _norm_paren(raw_assist) if raw_assist not in ("None", "") else None

    # Treat literal "None" ratchet (X-Over combos without a standard ratchet) as absent
    raw_ratchet = meta_row["ratchet"]
    ratchet_skip = raw_ratchet in ("None", "")

    blade_part = lookups["blade"].get(blade_key)
    ratchet_part = lookups["ratchet"].get(ratchet_key) if not ratchet_skip else None
    bit_part = lookups["bit"].get(bit_key)
    assist_part = lookups["assist-blade"].get(assist_key) if assist_key else None

    # Track unmatched names for the summary report
    if blade_part is None:
        unmatched["blade"].add(meta_row["blade"])
    if ratchet_part is None and not ratchet_skip:
        unmatched["ratchet"].add(raw_ratchet)
    if bit_part is None:
        unmatched["bit"].add(meta_row["bit"])
    if assist_key and assist_part is None:
        unmatched["assist_blade"].add(raw_assist)

    enriched = dict(meta_row)
    enriched.update(_prefix_cols(blade_part, BLADE_COLS, "blade"))
    enriched.update(_prefix_cols(ratchet_part, RATCHET_COLS, "ratchet"))
    enriched.update(_prefix_cols(bit_part, BIT_COLS, "bit"))
    enriched.update(_prefix_cols(assist_part, ASSIST_COLS, "assist"))
    return enriched


# ── Main ───────────────────────────────────────────────────────────────────────

def run(parts_path: Path, meta_path: Path, output_path: Path) -> None:
    log.info("Building part lookups from '%s' …", parts_path)
    lookups = build_lookups(parts_path)

    log.info("Loading meta rows from '%s' …", meta_path)
    with meta_path.open(newline="", encoding="utf-8") as fh:
        meta_rows = list(csv.DictReader(fh))
    log.info("  %d meta rows loaded", len(meta_rows))

    unmatched: dict[str, set] = {
        "blade": set(), "ratchet": set(), "bit": set(), "assist_blade": set()
    }

    enriched_rows = [enrich_row(r, lookups, unmatched) for r in meta_rows]

    # Determine output column order
    fieldnames = list(enriched_rows[0].keys()) if enriched_rows else []

    with output_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(enriched_rows)

    log.info("Wrote %d rows → '%s'", len(enriched_rows), output_path)

    # Report any unmatched names
    for cat, names in unmatched.items():
        if names:
            log.warning("Unmatched %s names (%d): %s", cat, len(names), sorted(names))
        else:
            log.info("  %s: all matched ✓", cat)


def main() -> None:
    parser = argparse.ArgumentParser(description="Join Beyblade parts specs into meta analytics CSV.")
    parser.add_argument("--parts", default="beyblade_parts.csv", help="Parts library CSV")
    parser.add_argument("--meta", default="beyblade_meta_analytics.csv", help="Meta analytics CSV")
    parser.add_argument("--output", default="beyblade_combined.csv", help="Output CSV")
    args = parser.parse_args()

    run(
        parts_path=Path(args.parts),
        meta_path=Path(args.meta),
        output_path=Path(args.output),
    )


if __name__ == "__main__":
    main()
