# Generated by GitHub Copilot
"""
Streamlit entry point for the Beyblade Analytics App.

Run with:
    streamlit run main.py
"""

import sys
from pathlib import Path

# Ensure the workspace root is on the Python path so that `app` and `ml`
# packages are importable regardless of the working directory.
sys.path.insert(0, str(Path(__file__).resolve().parent))

import streamlit as st
from app.seed import ensure_seeded

# Auto-seed the SQLite DB from CSVs on first boot (required on Streamlit Cloud
# where beyblade.db is not committed to the repository).
ensure_seeded()

st.set_page_config(
    page_title="Beyblade Analytics",
    page_icon="🌀",
    layout="wide",
    initial_sidebar_state="expanded",
)

dashboard = st.Page("app/pages/1_Dashboard.py", title="Dashboard", icon="📊", default=True)
parts = st.Page("app/pages/2_Parts_Catalog.py", title="Parts Catalog", icon="🔧")
rankings = st.Page("app/pages/3_Meta_Rankings.py", title="Meta Rankings", icon="🏆")
builder = st.Page("app/pages/4_Combo_Builder.py", title="Combo Builder", icon="⚙️")
ml_page = st.Page("app/pages/5_ML_Analysis.py", title="ML Analysis", icon="🤖")

pg = st.navigation([dashboard, parts, rankings, builder, ml_page])
pg.run()
