"""
Generate two normalised CSVs from beyblade_combined.csv:
  - combos.csv          : one row per unique combo (identity + denorm part specs)
  - combo_performance.csv : one row per (combo_key, season) performance record

Generated by GitHub Copilot
"""
import csv
from pathlib import Path

SRC = Path("beyblade_combined.csv")
OUT_COMBOS = Path("combos.csv")
OUT_PERF = Path("combo_performance.csv")

COMBO_FIELDS = [
    "combo_key",
    "combo_url_base",
    "blade",
    "assist_blade",
    "ratchet",
    "bit",
    "lock_chip",
    # denormalised part specs (static — same regardless of season)
    "blade_type",
    "blade_spin",
    "blade_weight_g",
    "blade_contact_points",
    "ratchet_weight_g",
    "ratchet_gears",
    "ratchet_burst_resistance",
    "bit_type",
    "bit_weight_g",
    "bit_height_mm",
    "assist_type",
    "assist_weight_g",
    "assist_high_level_mm",
]

PERF_FIELDS = [
    "combo_key",
    "season",
    "rank",
    "score",
    "placements_1st",
    "placements_2nd",
    "placements_3rd",
    "placements_4th",
    "total_placements",
    "win_rate",
    "podium_rate",
    "combo_url",
]


def strip_season_param(url: str) -> str:
    """Return the URL without the ?season=... query string."""
    return url.split("?")[0] if url else ""


def main() -> None:
    with open(SRC, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    # --- combos.csv: deduplicate by combo_key, keep first occurrence for specs ---
    seen: dict[str, dict] = {}
    for row in rows:
        key = row["combo_key"]
        if key not in seen:
            seen[key] = {
                "combo_key": key,
                "combo_url_base": strip_season_param(row["combo_url"]),
                "blade": row["blade"],
                "assist_blade": row["assist_blade"],
                "ratchet": row["ratchet"],
                "bit": row["bit"],
                "lock_chip": row["lock_chip"],
                "blade_type": row["blade_type"],
                "blade_spin": row["blade_spin"],
                "blade_weight_g": row["blade_weight_g"],
                "blade_contact_points": row["blade_contact_points"],
                "ratchet_weight_g": row["ratchet_weight_g"],
                "ratchet_gears": row["ratchet_gears"],
                "ratchet_burst_resistance": row["ratchet_burst_resistance"],
                "bit_type": row["bit_type"],
                "bit_weight_g": row["bit_weight_g"],
                "bit_height_mm": row["bit_height_mm"],
                "assist_type": row["assist_type"],
                "assist_weight_g": row["assist_weight_g"],
                "assist_high_level_mm": row["assist_high_level_mm"],
            }

    with open(OUT_COMBOS, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=COMBO_FIELDS)
        writer.writeheader()
        writer.writerows(seen.values())

    print(f"combos.csv         → {len(seen)} unique combos")

    # --- combo_performance.csv: one row per (combo_key, season) ---
    performances = []
    for row in rows:
        performances.append({
            "combo_key": row["combo_key"],
            "season": row["season"],
            "rank": row["rank"],
            "score": row["score"],
            "placements_1st": row["placements_1st"],
            "placements_2nd": row["placements_2nd"],
            "placements_3rd": row["placements_3rd"],
            "placements_4th": row["placements_4th"],
            "total_placements": row["total_placements"],
            "win_rate": row["win_rate"],
            "podium_rate": row["podium_rate"],
            "combo_url": row["combo_url"],
        })

    with open(OUT_PERF, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=PERF_FIELDS)
        writer.writeheader()
        writer.writerows(performances)

    print(f"combo_performance.csv → {len(performances)} performance records")


if __name__ == "__main__":
    main()
