#!/usr/bin/env python3
# Generated by GitHub Copilot
"""
scraper_meta.py — Beyblade X Meta Analytics Scraper (beybladexmeta.com)

Calls the REST API backend of beybladexmeta.com directly (no browser needed)
to collect all ranked combo statistics and writes an analytics-ready CSV.

Discovered via network inspection:
  GET /api/stats/combos?sortBy=score&sortOrder=desc&season={season}&page=1&limit=200

CSV schema — one row per ranked combo, per season:
  Identity     : rank, season, combo_key, combo_url
  Parts        : blade, assist_blade, ratchet, bit, lock_chip
  Performance  : score, placements_1st, placements_2nd,
                 placements_3rd, placements_4th
  Computed     : total_placements, win_rate, podium_rate

Usage:
  python scraper_meta.py                          # All Time season
  python scraper_meta.py --all-seasons            # all 3 seasons
  python scraper_meta.py --season "Season 2026"
  python scraper_meta.py --output my_meta.csv

Requires:
  pip install requests   (already in requirements.txt)
"""

from __future__ import annotations

import argparse
import csv
import logging
import sys
import time
from dataclasses import asdict, dataclass, fields as dc_fields
from urllib.parse import quote_plus

import requests

# ── Constants ──────────────────────────────────────────────────────────────────

BASE_URL = "https://beybladexmeta.com"
SEASONS_ENDPOINT = f"{BASE_URL}/api/seasons"
COMBOS_ENDPOINT = (
    f"{BASE_URL}/api/stats/combos"
    "?sortBy=score&sortOrder=desc&season={season}&page=1&limit=200"
)
COMBO_URL_TEMPLATE = f"{BASE_URL}/combo/{{key}}?season={{season}}"

REQUEST_TIMEOUT = 20
CRAWL_DELAY = 0.5
DEFAULT_SEASON = "All Time"
DEFAULT_OUTPUT = "beyblade_meta_analytics.csv"

log = logging.getLogger(__name__)

# ── HTTP session ───────────────────────────────────────────────────────────────

_http = requests.Session()
_http.headers.update({
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/122.0.0.0 Safari/537.36"
    ),
    "Accept": "application/json, text/plain, */*",
    "Referer": f"{BASE_URL}/analytics",
})


# ── Data model ─────────────────────────────────────────────────────────────────

# Generated by GitHub Copilot
@dataclass
class MetaCombo:
    """
    One row of the meta analytics CSV — one ranked combo entry.

    Field names follow the API JSON keys, translated to English snake_case:
      punteggioTotale → score
      primiPosti      → placements_1st
      secondiPosti    → placements_2nd
      terziPosti      → placements_3rd
      quartiPosti     → placements_4th

    win_rate and podium_rate are float strings rounded to 4 d.p.
    Empty string when total_placements == 0 (division-by-zero guard).
    """

    # --- Identity ---
    rank: int = 0
    season: str = ""
    combo_key: str = ""        # "{blade}|{assist_blade}|{ratchet}|{bit}|{lock_chip}"
    combo_url: str = ""        # Full detail page URL

    # --- Parts ---
    blade: str = ""
    assist_blade: str = ""     # API key: assistBlade
    ratchet: str = ""
    bit: str = ""
    lock_chip: str = ""        # API key: lockChip  (CX hybrid ratchet component)

    # --- Tournament performance ---
    score: int = 0             # API: punteggioTotale
    placements_1st: int = 0    # API: primiPosti
    placements_2nd: int = 0    # API: secondiPosti
    placements_3rd: int = 0    # API: terziPosti
    placements_4th: int = 0    # API: quartiPosti

    # --- Computed metrics ---
    total_placements: int = 0
    win_rate: str = ""         # placements_1st / total_placements
    podium_rate: str = ""      # (1st+2nd+3rd) / total_placements


CSV_COLUMNS: list[str] = [f.name for f in dc_fields(MetaCombo)]


# ── Helpers ────────────────────────────────────────────────────────────────────

def _compute_rates(p1: int, p2: int, p3: int, p4: int) -> tuple[str, str]:
    """
    Compute win_rate and podium_rate as formatted float strings.
    Guards against division-by-zero by returning ('', '') when total == 0.
    """
    total = p1 + p2 + p3 + p4
    if total == 0:
        return "", ""
    return str(round(p1 / total, 4)), str(round((p1 + p2 + p3) / total, 4))


def _build_combo_key(blade: str, assist: str, ratchet: str, bit: str, chip: str) -> str:
    """Build the pipe-delimited combo key matching the website's URL format."""
    return f"{blade}|{assist}|{ratchet}|{bit}|{chip}"


# ── API calls ──────────────────────────────────────────────────────────────────

def fetch_seasons() -> list[str]:
    """
    Retrieve the list of available seasons from the API.
    Returns a fallback list on error so the scraper can still run.

    Security: the endpoint is a fixed URL with no user input interpolated.
    The response is accessed via a strict key — any unexpected JSON shape is
    caught and logged rather than allowed to propagate.
    """
    try:
        resp = _http.get(SEASONS_ENDPOINT, timeout=REQUEST_TIMEOUT)
        resp.raise_for_status()
        data = resp.json()
        seasons = data.get("seasons", [])
        log.info("Available seasons: %s", seasons)
        return seasons
    except Exception as exc:
        log.error("Could not fetch seasons: %s", exc)
        return [DEFAULT_SEASON]


def fetch_combos_for_season(season: str) -> list[MetaCombo]:
    """
    Fetch all combo statistics for *season* in a single API request
    (limit=200 retrieves all 185+ combos in one round-trip).

    Security:
      - *season* is URL-encoded via quote_plus before interpolation.
      - The response JSON is parsed with strict key access; unexpected
        structures are caught per-entry and logged.
      - No shell commands, no file writes here — side-effect free.
    """
    url = COMBOS_ENDPOINT.format(season=quote_plus(season))
    log.info("Fetching combos for season '%s' …  %s", season, url)

    try:
        resp = _http.get(url, timeout=REQUEST_TIMEOUT)
        resp.raise_for_status()
        data = resp.json()
    except Exception as exc:
        log.error("API request failed for season '%s': %s", season, exc)
        return []

    raw_combos: list[dict] = data.get("combos", [])
    log.info("  → %d combos returned by API", len(raw_combos))

    result: list[MetaCombo] = []
    for rank, entry in enumerate(raw_combos, 1):
        try:
            blade = entry["blade"]
            assist = entry["assistBlade"]
            ratchet = entry["ratchet"]
            bit = entry["bit"]
            chip = entry["lockChip"]

            p1 = int(entry["primiPosti"])
            p2 = int(entry["secondiPosti"])
            p3 = int(entry["terziPosti"])
            p4 = int(entry["quartiPosti"])
            total = p1 + p2 + p3 + p4
            win_rate, podium_rate = _compute_rates(p1, p2, p3, p4)

            key = _build_combo_key(blade, assist, ratchet, bit, chip)
            combo_url = COMBO_URL_TEMPLATE.format(
                key=quote_plus(key).replace("%7C", "|"),  # keep | readable in URL
                season=quote_plus(season),
            )

            result.append(MetaCombo(
                rank=rank,
                season=season,
                combo_key=key,
                combo_url=combo_url,
                blade=blade,
                assist_blade=assist,
                ratchet=ratchet,
                bit=bit,
                lock_chip=chip,
                score=int(entry["punteggioTotale"]),
                placements_1st=p1,
                placements_2nd=p2,
                placements_3rd=p3,
                placements_4th=p4,
                total_placements=total,
                win_rate=win_rate,
                podium_rate=podium_rate,
            ))
        except (KeyError, ValueError, TypeError) as exc:
            log.warning("Skipping malformed combo entry (rank ~%d): %s", rank, exc)

    return result


# ── Main orchestration ─────────────────────────────────────────────────────────

def run(seasons: list[str], output_path: str) -> None:
    """
    Scrape all requested seasons and write the combined results to *output_path*.

    A short delay is inserted between season requests to be polite.
    """
    all_combos: list[MetaCombo] = []

    for i, season in enumerate(seasons):
        combos = fetch_combos_for_season(season)
        all_combos.extend(combos)
        log.info("  Season '%s': %d combos  (total so far: %d)", season, len(combos), len(all_combos))
        if i < len(seasons) - 1:
            time.sleep(CRAWL_DELAY)

    log.info("Writing %d rows → %s", len(all_combos), output_path)

    with open(output_path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=CSV_COLUMNS, extrasaction="ignore")
        writer.writeheader()
        for combo in all_combos:
            writer.writerow(asdict(combo))

    log.info("Done.  %d rows written to '%s'.", len(all_combos), output_path)


def main() -> None:
    """
    CLI entry point — parse arguments, configure logging, launch scraper.

    Input validation:
      - --season is a free string, only used as a URL query parameter
        (no SQL / shell injection surface).
      - --all-seasons fetches the season list from the API at runtime.
    """
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(levelname)-8s  %(message)s",
        datefmt="%H:%M:%S",
        stream=sys.stdout,
    )

    parser = argparse.ArgumentParser(
        description="Scrape Beyblade X meta combo rankings from beybladexmeta.com API",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python scraper_meta.py\n"
            "  python scraper_meta.py --all-seasons\n"
            '  python scraper_meta.py --season "Season 2026"\n'
            "  python scraper_meta.py --output meta.csv\n"
        ),
    )
    parser.add_argument(
        "--output", "-o",
        default=DEFAULT_OUTPUT,
        metavar="FILE",
        help=f"Output CSV path  (default: {DEFAULT_OUTPUT})",
    )
    season_group = parser.add_mutually_exclusive_group()
    season_group.add_argument(
        "--season", "-s",
        default=DEFAULT_SEASON,
        metavar="SEASON",
        help=f'Season to scrape  (default: "{DEFAULT_SEASON}")',
    )
    season_group.add_argument(
        "--all-seasons",
        action="store_true",
        help="Scrape all available seasons (fetched from /api/seasons)",
    )

    args = parser.parse_args()

    if args.all_seasons:
        seasons = fetch_seasons()
    else:
        seasons = [args.season]

    run(seasons, args.output)


if __name__ == "__main__":
    main()

