#!/usr/bin/env python3
# Generated by GitHub Copilot
"""
scraper.py — Beyblade X Parts Database Scraper

Crawls https://bey-library.vercel.app across all 7 part categories and
writes an analytics-ready CSV to `beyblade_parts.csv` (or a custom path).

Schema summary (one row per part):
  Identity   : part_id, name, category, is_beyblade_part,
               product_code_full, product_line, product_number,
               source_url, variant_count
  Gameplay   : type, spin, weight_g
  Blade      : stock_combo, stock_combo_ratchet, stock_combo_bit
  Ratchet    : contact_points, height_mm
  Bit        : gears, burst_resistance
  Assist-blade: high_level_mm

Usage:
  python scraper.py
  python scraper.py --output my_parts.csv
  python scraper.py --categories blade ratchet bit

Dependencies:
  pip install requests beautifulsoup4 lxml

NOTE: If spec fields are empty after a run, the site may have switched to
client-side rendering (CSR). In that case swap `_fetch()` for a Playwright
headless-browser fetch (`playwright.sync_api.sync_playwright`).
"""

from __future__ import annotations

import argparse
import csv
import logging
import re
import sys
import time
from dataclasses import asdict, dataclass, fields as dc_fields
from typing import Iterator, Optional
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup, NavigableString, Tag

# ── Constants ──────────────────────────────────────────────────────────────────

BASE_URL = "https://bey-library.vercel.app"
CRAWL_DELAY: float = 0.6       # polite pause between requests (seconds)
REQUEST_TIMEOUT: int = 20      # per-request socket timeout (seconds)

ALL_CATEGORIES: list[str] = [
    "blade",
    "over-blade",
    "assist-blade",
    "ratchet",
    "bit",
    "x-over",
    "other",
]

# Categories whose products are actual playable Beyblade parts (not accessories)
PLAYABLE: set[str] = {"blade", "over-blade", "assist-blade", "ratchet", "bit", "x-over"}

DEFAULT_OUTPUT = "beyblade_parts.csv"

# Spec keys that appear in concatenated spec text — longest first to avoid
# partial regex matches (e.g. "Weight" must not match inside "Burst Resistance")
_SPEC_KEYS: list[str] = [
    "Burst Resistance",
    "Stock Combo",
    "Product Line",
    "High Level",
    "Weight",
    "Gears",
    "Spin",
    "Type",
]

# Generated by GitHub Copilot
_SPEC_SPLIT_RE = re.compile(
    r"(" + "|".join(re.escape(k) for k in _SPEC_KEYS) + r")"
)

_PRODUCT_CODE_RE = re.compile(r"^(BX|UX|CX)[-\s](.*)$", re.IGNORECASE)
_CODE_BODY_RE = re.compile(r"^\s*(BX|UX|CX)-(\d+)\s*$", re.IGNORECASE)
_WEIGHT_RE = re.compile(r"~?([\d.]+)\s*[gG]\b")
_LEVEL_RE = re.compile(r"~?([\d.]+)\s*[mM][mM]")

# ── Data model ─────────────────────────────────────────────────────────────────

# Generated by GitHub Copilot
@dataclass
class BeyPart:
    """
    One row of the output CSV — one Beyblade X part or accessory.

    Category-specific columns that do not apply to a given part are left as
    empty strings so that downstream tools (pandas, Excel, etc.) treat them as
    null/NaN cleanly.
    """

    # --- Identity & classification ---
    part_id: str = ""              # URL slug, e.g. "Blade-DS-001"
    name: str = ""                 # Human-readable name, Title Case
    category: str = ""            # blade / ratchet / bit / over-blade / assist-blade / x-over / other
    is_beyblade_part: bool = True  # False for accessories (category == "other")
    product_code_full: str = ""   # Raw release code, e.g. "BX-01" or "Collab Star Wars"
    product_line: str = ""        # Parsed line: BX / UX / CX / Collab / 25th Anniversary …
    product_number: str = ""      # Numeric portion only, e.g. "01"; empty for special codes
    source_url: str = ""          # Canonical product page URL
    variant_count: int = 0        # Count of colour / recolour variants listed

    # --- Gameplay stats (shared across all playable categories) ---
    type: str = ""                # Attack / Defense / Stamina / Balance
    spin: str = ""                # Right / Left / Both
    weight_g: str = ""            # Normalised float string, e.g. "35.0"; empty when unknown

    # --- Blade-specific ---
    stock_combo: str = ""             # e.g. "3-60 Flat"
    stock_combo_ratchet: str = ""     # Parsed ratchet code, e.g. "3-60"
    stock_combo_bit: str = ""         # Parsed bit name, e.g. "Flat"

    # --- Ratchet-specific ---
    contact_points: str = ""      # Number of contact points, e.g. "3"
    height_mm: str = ""           # Ratchet height in mm, e.g. "6.0"

    # --- Bit-specific ---
    gears: str = ""               # Gear count, e.g. "1" or "2"
    burst_resistance: str = ""    # High / Low / Medium

    # --- Assist-blade-specific ---
    high_level_mm: str = ""       # Assist blade height in mm, e.g. "9.0"


CSV_COLUMNS: list[str] = [f.name for f in dc_fields(BeyPart)]

# ── HTTP session ───────────────────────────────────────────────────────────────

# Generated by GitHub Copilot
_http = requests.Session()
_http.headers.update({
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/122.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
})

log = logging.getLogger(__name__)


# ── HTTP helpers ───────────────────────────────────────────────────────────────

def _fetch(url: str) -> Optional[BeautifulSoup]:
    """
    GET *url* and return a parsed BeautifulSoup object, or None on any error.

    Security: enforces a sensible timeout; all exceptions are caught and logged
    rather than propagated, so a single bad page cannot abort the whole run.
    Warns when the page has no structural headings (sign of CSR / empty shell).
    """
    try:
        resp = _http.get(url, timeout=REQUEST_TIMEOUT)
        resp.raise_for_status()
    except requests.RequestException as exc:
        log.error("HTTP error fetching %s — %s", url, exc)
        return None

    soup = BeautifulSoup(resp.text, "lxml")

    # Detect potential client-side rendering
    if not soup.find(["h1", "h2", "h3"]):
        log.warning(
            "No structural headings found at %s. "
            "Page may require JavaScript (CSR). "
            "If spec data is missing, consider using Playwright instead of requests.",
            url,
        )
    return soup


# ── DOM traversal helpers ──────────────────────────────────────────────────────

def _siblings_until_heading(node: Tag | NavigableString) -> Iterator[str]:
    """
    Yield non-empty stripped text for all siblings of *node* until the next
    heading element (h1–h6).  Used to extract the body of a named section.
    """
    for sibling in node.next_siblings:
        if isinstance(sibling, Tag):
            if sibling.name in ("h1", "h2", "h3", "h4", "h5", "h6"):
                return
            text = sibling.get_text(separator=" ", strip=True)
            if text:
                yield text
        elif isinstance(sibling, NavigableString):
            text = sibling.strip()
            if text:
                yield text


def _section_text(soup: BeautifulSoup, heading: str) -> str:
    """
    Locate an <h3> whose text contains *heading* (case-insensitive) and
    return combined text of all following content up to the next heading.

    Strategy A — direct siblings of the <h3>.
    Strategy B — siblings of the <h3>'s parent element (handles cases where
                 the heading and its content live in separate wrapper divs).
    """
    for h3 in soup.find_all("h3"):
        if heading.upper() not in h3.get_text().upper():
            continue

        # Strategy A: h3 siblings
        chunks = list(_siblings_until_heading(h3))
        if chunks:
            return " ".join(chunks)

        # Strategy B: parent's siblings
        parent = h3.parent
        if parent and parent.name not in ("body", "html", "[document]"):
            chunks = list(_siblings_until_heading(parent))
            if chunks:
                return " ".join(chunks)

    return ""


# ── Spec parsers ───────────────────────────────────────────────────────────────

def _parse_spec_dict(raw: str) -> dict[str, str]:
    """
    Split concatenated spec text (e.g. 'TypeAttackSpinRightWeight~35 g…')
    into a labelled dict: {'Type': 'Attack', 'Spin': 'Right', 'Weight': '~35 g', …}.

    Uses _SPEC_SPLIT_RE (a regex of all known spec-key labels) to identify
    boundaries between key–value pairs in the otherwise-delimiter-free string.
    """
    parts = _SPEC_SPLIT_RE.split(raw)
    # Layout after split:  ['prefix', 'Key1', 'val1', 'Key2', 'val2', …]
    result: dict[str, str] = {}
    for i in range(1, len(parts) - 1, 2):
        key = parts[i].strip()
        val = parts[i + 1].strip()
        if key:
            result[key] = val
    return result


def _parse_ratchet_features(text: str) -> dict[str, str]:
    """
    Parse ratchet bullet-point feature text:
      '• 3 Contact Points  • High : 6.0 mm  • Weight: ~6 g'
    Returns a dict with any of: contact_points, height_mm, weight_g.
    All numeric values are normalised to float strings (e.g. '6.0').
    """
    result: dict[str, str] = {}

    m = re.search(r"(\d+)\s+Contact\s+Points", text, re.IGNORECASE)
    if m:
        result["contact_points"] = m.group(1)

    m = re.search(r"High\s*[:\-]?\s*~?([\d.]+)\s*mm", text, re.IGNORECASE)
    if m:
        result["height_mm"] = str(float(m.group(1)))

    m = re.search(r"Weight\s*[:\-]?\s*~?([\d.]+)\s*g\b", text, re.IGNORECASE)
    if m:
        result["weight_g"] = str(float(m.group(1)))

    return result


def _normalize_weight(raw: str) -> str:
    """
    Extract a numeric weight from strings like '~35 g' → '35.0'.
    Returns '' when no recognisable value is found.
    """
    m = _WEIGHT_RE.search(raw)
    return str(float(m.group(1))) if m else ""


def _normalize_level(raw: str) -> str:
    """
    Extract a numeric millimetre value from strings like '~9 MM' → '9.0'.
    Returns '' when no recognisable value is found.
    """
    m = _LEVEL_RE.search(raw)
    return str(float(m.group(1))) if m else ""


def _split_product_code(raw: str) -> tuple[str, str]:
    """
    Decompose a product release code into (product_line, product_number).

    Examples:
      'BX-01'              → ('BX', '01')
      'UX-14'              → ('UX', '14')
      'CX-Rare Bey Battle' → ('CX', '')
      'Collab Star Wars'   → ('Collab Star Wars', '')
      '25th Anniversary'   → ('25th Anniversary', '')
      'BX-00 (DMM Lottey)' → ('BX', '')
    """
    raw = raw.strip()
    m = _PRODUCT_CODE_RE.match(raw)
    if m:
        line = m.group(1).upper()
        rest = m.group(2).strip()
        # product_number only when the remainder is purely numeric
        number = rest if re.match(r"^\d+$", rest) else ""
        return line, number
    return raw, ""


# ── Product-code extraction ────────────────────────────────────────────────────

def _extract_product_code(soup: BeautifulSoup) -> str:
    """
    Locate the product release code on a product detail page.

    The code (e.g. 'BX-01', 'Collab Star Wars', '25th Anniversary') typically
    appears immediately after the <h1> and before the first <h3> section heading.

    Security: only text matching known code patterns is accepted; arbitrary
    navigation link text is ignored.
    """
    h1 = soup.find("h1")
    if h1 is None:
        return ""

    # Walk siblings of h1 until the first section heading
    for node in h1.next_siblings:
        if isinstance(node, Tag):
            if node.name in ("h2", "h3", "h4", "h5", "h6"):
                break
            text = node.get_text(strip=True)
        elif isinstance(node, NavigableString):
            text = node.strip()
        else:
            continue

        if not text:
            continue

        # Standard codes: BX-01, UX-14, CX-10, BX-Rare Bey Battle, etc.
        if re.match(r"^(BX|UX|CX)[-\s]", text, re.IGNORECASE):
            return text

        # Non-standard labels without a BX/UX/CX prefix
        if re.search(
            r"\b(Anniversary|Collab|Limited|Lottery|Comic|Package|Battle|Collaboration)\b",
            text, re.IGNORECASE,
        ):
            return text

    # Fallback: scan body text for a pure standard numeric code
    for el in soup.find_all(string=_CODE_BODY_RE):
        text = el.strip()
        if text:
            return text

    return ""


# ── Variant count ──────────────────────────────────────────────────────────────

def _count_variants(soup: BeautifulSoup) -> int:
    """
    Count variant images in the VARIANTS section of a product detail page.
    Returns 0 when the section is absent.
    """
    for h3 in soup.find_all("h3"):
        if "VARIANTS" not in h3.get_text().upper():
            continue
        count = 0
        for node in h3.next_siblings:
            if isinstance(node, Tag):
                if node.name in ("h1", "h2", "h3", "h4"):
                    break
                count += len(node.find_all("img"))
        return count
    return 0


# ── Category page scraping ─────────────────────────────────────────────────────

def get_product_urls(category: str) -> list[str]:
    """
    Fetch the category listing page and return all unique product detail URLs.

    Security: only hrefs that start with the expected '/product/{category}/'
    path prefix are accepted. This acts as a strict whitelist and prevents
    open-redirect or path-traversal via malicious anchor tags.
    """
    page_url = f"{BASE_URL}/category/{category}"
    log.info("Fetching category '%s'  →  %s", category, page_url)
    soup = _fetch(page_url)
    if soup is None:
        return []

    allowed_prefix = f"/product/{category}/"
    seen: set[str] = set()
    urls: list[str] = []

    for a_tag in soup.find_all("a", href=True):
        href: str = a_tag["href"]
        # Normalise absolute same-origin URLs to path-only
        if href.startswith(BASE_URL):
            href = href[len(BASE_URL):]
        # Strict path whitelist
        if href.startswith(allowed_prefix):
            full = BASE_URL + href
            if full not in seen:
                seen.add(full)
                urls.append(full)

    log.info("    → %d unique product URLs found", len(urls))
    return urls


# ── Product page scraping ──────────────────────────────────────────────────────

def scrape_product(url: str, category: str) -> Optional[BeyPart]:
    """
    Scrape one product detail page and return a fully populated BeyPart.

    Returns None when the page cannot be fetched.
    Dispatches to category-specific spec parsers for ratchets (bullet-point
    feature format) versus all other playable parts (concatenated spec format).
    The 'other' (accessories) category skips gameplay spec parsing entirely.
    """
    soup = _fetch(url)
    if soup is None:
        return None

    part = BeyPart()
    part.source_url = url
    part.category = category
    part.is_beyblade_part = category in PLAYABLE
    part.part_id = url.rstrip("/").split("/")[-1]

    # --- Name ---
    h1 = soup.find("h1")
    raw_name = h1.get_text(strip=True) if h1 else part.part_id
    part.name = raw_name.title()

    # --- Product code ---
    raw_code = _extract_product_code(soup)
    part.product_code_full = raw_code
    part.product_line, part.product_number = _split_product_code(raw_code)

    # --- Variant count ---
    part.variant_count = _count_variants(soup)

    # --- Category-specific spec parsing ---
    if category == "ratchet":
        _apply_ratchet_specs(soup, part)
    elif category != "other":
        _apply_generic_specs(soup, part)
    # "other" (accessories) has no gameplay specs — all fields remain ""

    return part


def _apply_generic_specs(soup: BeautifulSoup, part: BeyPart) -> None:
    """
    Parse the SPECIFICATIONS section for blade, bit, over-blade, assist-blade,
    and x-over product pages.

    The spec text is a concatenation of key–value pairs with no delimiters,
    e.g. 'TypeAttackSpinRightWeight~35 gStock Combo3-60 FlatProduct LineBX'.
    _parse_spec_dict splits it via known key labels.
    """
    raw = _section_text(soup, "SPECIFICATIONS")
    specs = _parse_spec_dict(raw)

    part.type = specs.get("Type", "")
    part.spin = specs.get("Spin", "")
    part.weight_g = _normalize_weight(specs.get("Weight", ""))

    # Blade / x-over: stock combo
    part.stock_combo = specs.get("Stock Combo", "")
    if part.stock_combo:
        sc_m = re.match(r"^(\d+-\d+)\s+(.+)$", part.stock_combo.strip())
        if sc_m:
            part.stock_combo_ratchet = sc_m.group(1)
            part.stock_combo_bit = sc_m.group(2).strip()

    # Bit: gears and burst resistance
    part.gears = specs.get("Gears", "")
    part.burst_resistance = specs.get("Burst Resistance", "")

    # Assist-blade: high level
    part.high_level_mm = _normalize_level(specs.get("High Level", ""))


def _apply_ratchet_specs(soup: BeautifulSoup, part: BeyPart) -> None:
    """
    Parse specs for ratchet product pages.

    Ratchets use a bullet-point FEATURES section rather than the flat
    SPECIFICATIONS layout.  Additionally, contact_points and height_mm are
    derived directly from the ratchet's name (e.g. '3-60' → 3 points, 6.0 mm)
    as the primary — and most reliable — source.

    Naming edge cases handled:
      '3-60'      → contact_points='3', height_mm='6.0'
      'M-85'      → name doesn't match digit-digit, fall back to features text
      'Tr (Turbo)'→ hybrid ratchet, no contact/height from name
    """
    # Primary: derive from the "N-HH" name pattern (most ratchets)
    name_m = re.match(r"^(\d+)-(\d+)$", part.name.strip())
    if name_m:
        part.contact_points = name_m.group(1)
        part.height_mm = str(float(name_m.group(2)) / 10.0)

    # Secondary: parse FEATURES bullet text for weight + fallback contact/height
    feat_text = _section_text(soup, "FEATURES")
    if not feat_text:
        # Some pages may use SPECIFICATIONS heading even for ratchets
        feat_text = _section_text(soup, "SPECIFICATIONS")

    ratchet = _parse_ratchet_features(feat_text)

    if not part.contact_points and ratchet.get("contact_points"):
        part.contact_points = ratchet["contact_points"]
    if not part.height_mm and ratchet.get("height_mm"):
        part.height_mm = ratchet["height_mm"]
    if ratchet.get("weight_g"):
        part.weight_g = ratchet["weight_g"]


# ── Main orchestration ─────────────────────────────────────────────────────────

def run(categories: list[str], output_path: str) -> None:
    """
    Orchestrate the full scrape: iterate over all categories, collect product
    URLs, scrape each product page, then write everything to *output_path*.

    Progress is logged to stdout at INFO level.
    """
    all_parts: list[BeyPart] = []
    total = 0
    errors = 0

    for cat in categories:
        urls = get_product_urls(cat)
        total += len(urls)
        for idx, url in enumerate(urls, 1):
            slug = url.rstrip("/").split("/")[-1]
            log.info("  [%-12s] %3d/%-3d  %s", cat, idx, len(urls), slug)
            part = scrape_product(url, cat)
            if part:
                all_parts.append(part)
            else:
                errors += 1
            time.sleep(CRAWL_DELAY)

    log.info(
        "Scraped %d / %d parts  (%d errors).  Writing → %s",
        len(all_parts), total, errors, output_path,
    )

    with open(output_path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=CSV_COLUMNS, extrasaction="ignore")
        writer.writeheader()
        for part in all_parts:
            writer.writerow(asdict(part))

    log.info("Done.  %d rows written to '%s'.", len(all_parts), output_path)


def main() -> None:
    """
    CLI entry point — parse command-line arguments and launch the scraper.

    Input validation is handled by argparse (choices= for categories).
    """
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(levelname)-8s  %(message)s",
        datefmt="%H:%M:%S",
        stream=sys.stdout,
    )

    parser = argparse.ArgumentParser(
        description="Scrape Beyblade X parts from bey-library.vercel.app",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python scraper.py\n"
            "  python scraper.py --output parts.csv\n"
            "  python scraper.py --categories blade ratchet bit\n"
        ),
    )
    parser.add_argument(
        "--output", "-o",
        default=DEFAULT_OUTPUT,
        metavar="FILE",
        help=f"Output CSV file path  (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--categories", "-c",
        nargs="+",
        choices=ALL_CATEGORIES,
        default=ALL_CATEGORIES,
        metavar="CATEGORY",
        help=(
            f"Categories to scrape  (default: all).\n"
            f"Options: {', '.join(ALL_CATEGORIES)}"
        ),
    )

    args = parser.parse_args()
    run(args.categories, args.output)


if __name__ == "__main__":
    main()
