# Generated by GitHub Copilot
"""
SQLAlchemy engine and session factory for the Beyblade analytics app.
The database file is created at the workspace root as beyblade.db.
"""

import os
from pathlib import Path
from contextlib import contextmanager

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, DeclarativeBase

# Resolve DB path relative to the workspace root (two levels up from this file)
_DB_PATH = Path(__file__).resolve().parent.parent / "beyblade.db"
_DB_URL = f"sqlite:///{_DB_PATH}"

engine = create_engine(
    _DB_URL,
    connect_args={"check_same_thread": False},  # required for SQLite + Streamlit threading
    echo=False,
)

SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models."""
    pass


def get_db():
    """Yield a SQLAlchemy session and ensure it is closed on exit."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


@contextmanager
def db_session():
    """Context-manager wrapper around get_db() for non-generator callers."""
    session = SessionLocal()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()
