# Generated by GitHub Copilot
"""
SQLAlchemy ORM models for the Beyblade analytics database.

Three tables:
  - parts            → beyblade_parts.csv
  - combos           → combos.csv
  - combo_performance → combo_performance.csv (FK → combos.combo_key)
"""

from sqlalchemy import (
    Boolean,
    Column,
    Float,
    ForeignKey,
    Integer,
    String,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship

from app.database import Base


class Part(Base):
    """
    A single Beyblade component (blade, ratchet, bit, assist-blade, etc.).

    Maps to the ``parts`` table which is seeded from beyblade_parts.csv.
    """

    __tablename__ = "parts"

    part_id = Column(String, primary_key=True)
    name = Column(String, nullable=False)
    category = Column(String)              # blade | ratchet | bit | assist_blade | …
    is_beyblade_part = Column(Boolean)
    product_code_full = Column(String)
    product_line = Column(String)          # BX | UX | CX
    product_number = Column(String)
    source_url = Column(String)
    variant_count = Column(Integer)

    # Type / mechanical attributes (populated depending on category)
    type = Column(String)                  # Attack | Defense | Stamina | Balance
    spin = Column(String)                  # Right | Left
    weight_g = Column(Float)
    contact_points = Column(Integer)
    height_mm = Column(Float)
    gears = Column(Integer)
    burst_resistance = Column(String)      # High | Low

    # Blade-specific
    stock_combo = Column(String)
    stock_combo_ratchet = Column(String)
    stock_combo_bit = Column(String)

    # Assist-blade / over-blade specific
    high_level_mm = Column(Float)


class Combo(Base):
    """
    A unique Beyblade combo (blade + ratchet + bit + optional assist/lock-chip).

    Maps to the ``combos`` table seeded from combos.csv.
    Each row represents a distinct part configuration (no seasonal duplication).
    """

    __tablename__ = "combos"

    combo_key = Column(String, primary_key=True)  # pipe-delimited, e.g. "WizardRod|None|1-60|Hexa|None"
    combo_url_base = Column(String)
    blade = Column(String)
    assist_blade = Column(String)
    ratchet = Column(String)
    bit = Column(String)
    lock_chip = Column(String)

    # Denormalized part specs (joined at normalise time)
    blade_type = Column(String)
    blade_spin = Column(String)
    blade_weight_g = Column(Float)
    blade_contact_points = Column(Integer)

    ratchet_weight_g = Column(Float)
    ratchet_gears = Column(Integer)
    ratchet_burst_resistance = Column(String)

    bit_type = Column(String)
    bit_weight_g = Column(Float)
    bit_height_mm = Column(Float)

    assist_type = Column(String)
    assist_weight_g = Column(Float)
    assist_high_level_mm = Column(Float)

    # Relationship
    performances = relationship(
        "ComboPerformance",
        back_populates="combo",
        cascade="all, delete-orphan",
    )


class ComboPerformance(Base):
    """
    Seasonal performance record for a combo.

    Maps to ``combo_performance`` seeded from combo_performance.csv.
    One row per (combo_key, season) pair.
    """

    __tablename__ = "combo_performance"
    __table_args__ = (UniqueConstraint("combo_key", "season", name="uq_combo_season"),)

    id = Column(Integer, primary_key=True, autoincrement=True)
    combo_key = Column(String, ForeignKey("combos.combo_key"), nullable=False)
    season = Column(String, nullable=False)   # "Season 2026" | "Off Season 2025" | "All Time"
    rank = Column(Integer)
    score = Column(Float)
    placements_1st = Column(Integer)
    placements_2nd = Column(Integer)
    placements_3rd = Column(Integer)
    placements_4th = Column(Integer)
    total_placements = Column(Integer)
    win_rate = Column(Float)
    podium_rate = Column(Float)
    combo_url = Column(String)

    # Relationship
    combo = relationship("Combo", back_populates="performances")
