# Generated by GitHub Copilot
"""
Seed script: loads CSV data into the SQLite database (idempotent).

Usage (from workspace root):
    python app/seed.py

The script drops and recreates all tables on each run so it is safe to
re-execute after re-running the scrapers to pick up fresh data.
"""

import sys
from pathlib import Path

import pandas as pd

# Allow running as a top-level script from the workspace root
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.database import Base, engine
from app.models import Combo, ComboPerformance, Part  # noqa: F401 – needed for metadata

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_ROOT = Path(__file__).resolve().parent.parent
_PARTS_CSV = _ROOT / "beyblade_parts.csv"
_COMBOS_CSV = _ROOT / "combos.csv"
_PERF_CSV = _ROOT / "combo_performance.csv"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _to_bool(val) -> bool | None:
    """Convert truthy string values to Python bool."""
    if pd.isna(val):
        return None
    if isinstance(val, bool):
        return val
    return str(val).strip().lower() in {"true", "1", "yes"}


def _to_int_or_none(val) -> int | None:
    """Coerce to int, returning None for NaN / non-numeric values."""
    try:
        if pd.isna(val):
            return None
        return int(float(val))
    except (TypeError, ValueError):
        return None


def _to_float_or_none(val) -> float | None:
    """Coerce to float, returning None for NaN / non-numeric values."""
    try:
        if pd.isna(val):
            return None
        return float(val)
    except (TypeError, ValueError):
        return None


def _normalize_type(val: str | None) -> str | None:
    """Fix known typos in the 'type' controlled vocabulary."""
    if not val or (isinstance(val, float)):
        return None
    mapping = {"balacne": "Balance", "balance": "Balance"}
    cleaned = str(val).strip()
    return mapping.get(cleaned.lower(), cleaned)


# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------

def _load_parts(session) -> int:
    """Read beyblade_parts.csv and bulk-insert Part rows."""
    df = pd.read_csv(_PARTS_CSV, dtype=str)

    parts = []
    for _, row in df.iterrows():
        parts.append(
            Part(
                part_id=row["part_id"],
                name=row["name"],
                category=row.get("category"),
                is_beyblade_part=_to_bool(row.get("is_beyblade_part")),
                product_code_full=row.get("product_code_full"),
                product_line=row.get("product_line"),
                product_number=row.get("product_number"),
                source_url=row.get("source_url"),
                variant_count=_to_int_or_none(row.get("variant_count")),
                type=_normalize_type(row.get("type")),
                spin=row.get("spin") if pd.notna(row.get("spin")) else None,
                weight_g=_to_float_or_none(row.get("weight_g")),
                contact_points=_to_int_or_none(row.get("contact_points")),
                height_mm=_to_float_or_none(row.get("height_mm")),
                gears=_to_int_or_none(row.get("gears")),
                burst_resistance=row.get("burst_resistance") if pd.notna(row.get("burst_resistance")) else None,
                stock_combo=row.get("stock_combo") if pd.notna(row.get("stock_combo")) else None,
                stock_combo_ratchet=row.get("stock_combo_ratchet") if pd.notna(row.get("stock_combo_ratchet")) else None,
                stock_combo_bit=row.get("stock_combo_bit") if pd.notna(row.get("stock_combo_bit")) else None,
                high_level_mm=_to_float_or_none(row.get("high_level_mm")),
            )
        )

    session.bulk_save_objects(parts)
    return len(parts)


def _load_combos(session) -> int:
    """Read combos.csv and bulk-insert Combo rows."""
    df = pd.read_csv(_COMBOS_CSV, dtype=str)

    combos = []
    for _, row in df.iterrows():
        combos.append(
            Combo(
                combo_key=row["combo_key"],
                combo_url_base=row.get("combo_url_base") if pd.notna(row.get("combo_url_base")) else None,
                blade=row.get("blade") if pd.notna(row.get("blade")) else None,
                assist_blade=row.get("assist_blade") if pd.notna(row.get("assist_blade")) else None,
                ratchet=row.get("ratchet") if pd.notna(row.get("ratchet")) else None,
                bit=row.get("bit") if pd.notna(row.get("bit")) else None,
                lock_chip=row.get("lock_chip") if pd.notna(row.get("lock_chip")) else None,
                blade_type=_normalize_type(row.get("blade_type")),
                blade_spin=row.get("blade_spin") if pd.notna(row.get("blade_spin")) else None,
                blade_weight_g=_to_float_or_none(row.get("blade_weight_g")),
                blade_contact_points=_to_int_or_none(row.get("blade_contact_points")),
                ratchet_weight_g=_to_float_or_none(row.get("ratchet_weight_g")),
                ratchet_gears=_to_int_or_none(row.get("ratchet_gears")),
                ratchet_burst_resistance=row.get("ratchet_burst_resistance") if pd.notna(row.get("ratchet_burst_resistance")) else None,
                bit_type=_normalize_type(row.get("bit_type")),
                bit_weight_g=_to_float_or_none(row.get("bit_weight_g")),
                bit_height_mm=_to_float_or_none(row.get("bit_height_mm")),
                assist_type=_normalize_type(row.get("assist_type")),
                assist_weight_g=_to_float_or_none(row.get("assist_weight_g")),
                assist_high_level_mm=_to_float_or_none(row.get("assist_high_level_mm")),
            )
        )

    session.bulk_save_objects(combos)
    return len(combos)


def _load_performance(session) -> int:
    """Read combo_performance.csv and bulk-insert ComboPerformance rows."""
    df = pd.read_csv(_PERF_CSV, dtype=str)

    records = []
    for _, row in df.iterrows():
        records.append(
            ComboPerformance(
                combo_key=row["combo_key"],
                season=row["season"],
                rank=_to_int_or_none(row.get("rank")),
                score=_to_float_or_none(row.get("score")),
                placements_1st=_to_int_or_none(row.get("placements_1st")),
                placements_2nd=_to_int_or_none(row.get("placements_2nd")),
                placements_3rd=_to_int_or_none(row.get("placements_3rd")),
                placements_4th=_to_int_or_none(row.get("placements_4th")),
                total_placements=_to_int_or_none(row.get("total_placements")),
                win_rate=_to_float_or_none(row.get("win_rate")),
                podium_rate=_to_float_or_none(row.get("podium_rate")),
                combo_url=row.get("combo_url") if pd.notna(row.get("combo_url")) else None,
            )
        )

    session.bulk_save_objects(records)
    return len(records)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def seed():
    """Drop + recreate all tables, then load data from the three CSV files."""
    print("Dropping and recreating tables …")
    Base.metadata.drop_all(engine)
    Base.metadata.create_all(engine)

    from sqlalchemy.orm import Session

    with Session(engine) as session:
        n_parts = _load_parts(session)
        print(f"  ✓ parts:             {n_parts:>5} rows")

        n_combos = _load_combos(session)
        print(f"  ✓ combos:            {n_combos:>5} rows")

        n_perf = _load_performance(session)
        print(f"  ✓ combo_performance: {n_perf:>5} rows")

        session.commit()

    print(f"\nDatabase ready: {engine.url}")


def ensure_seeded() -> None:
    """
    Idempotent bootstrap for Streamlit Cloud (and fresh local checkouts).

    Creates tables if they do not exist, then seeds from the CSV files if the
    ``parts`` table is empty. Safe to call on every app startup — it is a
    no-op when the database is already populated.
    """
    from sqlalchemy import inspect, text
    from sqlalchemy.orm import Session

    # Always ensure schema exists (harmless if already present)
    Base.metadata.create_all(engine)

    inspector = inspect(engine)
    if "parts" not in inspector.get_table_names():
        # Tables were just created — seed unconditionally
        _do_seed()
        return

    with engine.connect() as conn:
        count = conn.execute(text("SELECT COUNT(*) FROM parts")).scalar()

    if count == 0:
        _do_seed()


def _do_seed() -> None:
    """Internal helper: load all CSVs into the (already-created) tables."""
    from sqlalchemy.orm import Session

    with Session(engine) as session:
        _load_parts(session)
        _load_combos(session)
        _load_performance(session)
        session.commit()

    print(f"Database seeded from CSVs → {engine.url}")


if __name__ == "__main__":
    seed()
