# Generated by GitHub Copilot
"""
Dashboard page: overview KPIs, top combos, and season comparison chart.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

import pandas as pd
import plotly.express as px
import streamlit as st
from sqlalchemy import func, text

from app.database import SessionLocal

st.title("📊 Dashboard")
st.caption("Overview of the Beyblade X meta database")


@st.cache_resource
def get_session():
    """Return a shared SQLAlchemy session (cached across reruns)."""
    return SessionLocal()


db = get_session()


# ---------------------------------------------------------------------------
# KPI row
# ---------------------------------------------------------------------------
col1, col2, col3, col4 = st.columns(4)

total_parts = db.execute(text("SELECT COUNT(*) FROM parts")).scalar()
total_combos = db.execute(text("SELECT COUNT(*) FROM combos")).scalar()
total_perf_rows = db.execute(text("SELECT COUNT(*) FROM combo_performance")).scalar()
seasons_count = db.execute(text("SELECT COUNT(DISTINCT season) FROM combo_performance")).scalar()

col1.metric("Total Parts", f"{total_parts:,}")
col2.metric("Unique Combos", f"{total_combos:,}")
col3.metric("Performance Records", f"{total_perf_rows:,}")
col4.metric("Seasons Tracked", seasons_count)

st.divider()


# ---------------------------------------------------------------------------
# Top 10 combos – Season 2026
# ---------------------------------------------------------------------------
st.subheader("🏆 Top 10 Combos — Season 2026")

top10_q = text("""
    SELECT
        cp.rank,
        cp.combo_key,
        c.blade,
        c.ratchet,
        c.bit,
        c.blade_type,
        cp.score,
        ROUND(cp.win_rate * 100, 1)  AS win_pct,
        ROUND(cp.podium_rate * 100, 1) AS podium_pct,
        cp.total_placements
    FROM combo_performance cp
    JOIN combos c ON c.combo_key = cp.combo_key
    WHERE cp.season = 'Season 2026'
    ORDER BY cp.rank
    LIMIT 10
""")
top10_df = pd.read_sql(top10_q, db.bind)
top10_df.columns = ["Rank", "Combo Key", "Blade", "Ratchet", "Bit", "Type",
                    "Score", "Win %", "Podium %", "Placements"]
st.dataframe(top10_df, use_container_width=True, hide_index=True)

st.divider()


# ---------------------------------------------------------------------------
# Avg win-rate by blade type across seasons
# ---------------------------------------------------------------------------
st.subheader("📈 Average Win Rate by Blade Type per Season")

winrate_q = text("""
    SELECT
        cp.season,
        c.blade_type,
        ROUND(AVG(cp.win_rate) * 100, 2) AS avg_win_rate_pct
    FROM combo_performance cp
    JOIN combos c ON c.combo_key = cp.combo_key
    WHERE c.blade_type IS NOT NULL
    GROUP BY cp.season, c.blade_type
    ORDER BY cp.season, c.blade_type
""")
winrate_df = pd.read_sql(winrate_q, db.bind)

if not winrate_df.empty:
    fig = px.bar(
        winrate_df,
        x="blade_type",
        y="avg_win_rate_pct",
        color="season",
        barmode="group",
        labels={"blade_type": "Blade Type", "avg_win_rate_pct": "Avg Win Rate (%)", "season": "Season"},
        color_discrete_sequence=px.colors.qualitative.Set2,
    )
    fig.update_layout(legend_title_text="Season", xaxis_title="Blade Type", yaxis_title="Avg Win Rate (%)")
    st.plotly_chart(fig, use_container_width=True)
else:
    st.info("No win-rate data available yet.")

st.divider()


# ---------------------------------------------------------------------------
# Parts breakdown by category
# ---------------------------------------------------------------------------
st.subheader("🔧 Parts by Category")

cat_q = text("SELECT category, COUNT(*) AS count FROM parts GROUP BY category ORDER BY count DESC")
cat_df = pd.read_sql(cat_q, db.bind)
cat_df.columns = ["Category", "Count"]

fig2 = px.pie(cat_df, names="Category", values="Count", color_discrete_sequence=px.colors.qualitative.Pastel)
fig2.update_traces(textposition="inside", textinfo="percent+label")
st.plotly_chart(fig2, use_container_width=True)
