# Generated by GitHub Copilot
"""
Parts Catalog page: browse and filter all Beyblade components.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

import pandas as pd
import streamlit as st
from sqlalchemy import text

from app.database import SessionLocal

st.title("🔧 Parts Catalog")
st.caption("Browse all scraped Beyblade X components")


@st.cache_resource
def get_session():
    """Return a shared SQLAlchemy session (cached across reruns)."""
    return SessionLocal()


db = get_session()

# ---------------------------------------------------------------------------
# Load all parts once (small table — safe to pull fully)
# ---------------------------------------------------------------------------
@st.cache_data(ttl=300)
def load_parts():
    """Load parts table as a DataFrame (cached for 5 minutes)."""
    q = text("""
        SELECT part_id, name, category, product_line, type, spin,
               weight_g, contact_points, height_mm, gears,
               burst_resistance, variant_count, source_url
        FROM parts
        ORDER BY category, name
    """)
    return pd.read_sql(q, db.bind)


df = load_parts()

# ---------------------------------------------------------------------------
# Sidebar filters
# ---------------------------------------------------------------------------
with st.sidebar:
    st.header("Filters")

    categories = ["All"] + sorted(df["category"].dropna().unique().tolist())
    sel_category = st.selectbox("Category", categories)

    types = ["All"] + sorted(df["type"].dropna().unique().tolist())
    sel_type = st.selectbox("Type", types)

    spins = ["All"] + sorted(df["spin"].dropna().unique().tolist())
    sel_spin = st.selectbox("Spin", spins)

    lines = ["All"] + sorted(df["product_line"].dropna().unique().tolist())
    sel_line = st.selectbox("Product Line", lines)

    name_filter = st.text_input("Search by name", placeholder="e.g. Wizard")

# ---------------------------------------------------------------------------
# Apply filters
# ---------------------------------------------------------------------------
filtered = df.copy()
if sel_category != "All":
    filtered = filtered[filtered["category"] == sel_category]
if sel_type != "All":
    filtered = filtered[filtered["type"] == sel_type]
if sel_spin != "All":
    filtered = filtered[filtered["spin"] == sel_spin]
if sel_line != "All":
    filtered = filtered[filtered["product_line"] == sel_line]
if name_filter:
    filtered = filtered[filtered["name"].str.contains(name_filter, case=False, na=False)]

st.markdown(f"**{len(filtered)}** parts found")

# ---------------------------------------------------------------------------
# Display table
# ---------------------------------------------------------------------------
display_cols = ["name", "category", "product_line", "type", "spin",
                "weight_g", "contact_points", "height_mm", "gears",
                "burst_resistance", "variant_count"]

st.dataframe(
    filtered[display_cols].rename(columns={
        "name": "Name", "category": "Category", "product_line": "Line",
        "type": "Type", "spin": "Spin", "weight_g": "Weight (g)",
        "contact_points": "Contact Points", "height_mm": "Height (mm)",
        "gears": "Gears", "burst_resistance": "Burst Resist.",
        "variant_count": "Variants",
    }),
    use_container_width=True,
    hide_index=True,
)

st.divider()

# ---------------------------------------------------------------------------
# Detail panel – select a part to see full record
# ---------------------------------------------------------------------------
st.subheader("Part Detail")
selected_name = st.selectbox(
    "Select a part to inspect",
    options=["—"] + filtered["name"].tolist(),
    label_visibility="collapsed",
)

if selected_name != "—":
    row = filtered[filtered["name"] == selected_name].iloc[0]
    c1, c2 = st.columns(2)
    with c1:
        st.markdown(f"**ID:** `{row['part_id']}`")
        st.markdown(f"**Category:** {row['category']}")
        st.markdown(f"**Product Line:** {row['product_line']}")
        st.markdown(f"**Type:** {row['type']}")
        st.markdown(f"**Spin:** {row['spin']}")
        st.markdown(f"**Weight:** {row['weight_g']} g")
    with c2:
        st.markdown(f"**Contact Points:** {row['contact_points']}")
        st.markdown(f"**Height:** {row['height_mm']} mm")
        st.markdown(f"**Gears:** {row['gears']}")
        st.markdown(f"**Burst Resistance:** {row['burst_resistance']}")
        st.markdown(f"**Variants:** {row['variant_count']}")
        if pd.notna(row.get("source_url")):
            st.markdown(f"[View on Bey-Library]({row['source_url']})")
