# Generated by GitHub Copilot
"""
Meta Rankings page: seasonal combo leaderboard with interactive filters and charts.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

import pandas as pd
import plotly.express as px
import streamlit as st
from sqlalchemy import text

from app.database import SessionLocal

st.title("🏆 Meta Rankings")
st.caption("Seasonal combo performance leaderboard")


@st.cache_resource
def get_session():
    """Return a shared SQLAlchemy session (cached across reruns)."""
    return SessionLocal()


db = get_session()


@st.cache_data(ttl=300)
def load_rankings():
    """Load combo performance joined with combo specs (cached 5 min)."""
    q = text("""
        SELECT
            cp.season,
            cp.rank,
            cp.combo_key,
            c.blade,
            c.ratchet,
            c.bit,
            c.assist_blade,
            c.blade_type,
            c.blade_spin,
            c.blade_weight_g,
            c.ratchet_weight_g,
            c.bit_weight_g,
            cp.score,
            cp.win_rate,
            cp.podium_rate,
            cp.total_placements,
            cp.placements_1st,
            cp.placements_2nd,
            cp.placements_3rd,
            cp.placements_4th,
            cp.combo_url
        FROM combo_performance cp
        JOIN combos c ON c.combo_key = cp.combo_key
        ORDER BY cp.season, cp.rank
    """)
    return pd.read_sql(q, db.bind)


df = load_rankings()

# ---------------------------------------------------------------------------
# Sidebar filters
# ---------------------------------------------------------------------------
with st.sidebar:
    st.header("Filters")

    seasons = sorted(df["season"].unique().tolist())
    sel_season = st.selectbox("Season", seasons)

    types = ["All"] + sorted(df["blade_type"].dropna().unique().tolist())
    sel_type = st.selectbox("Blade Type", types)

    spins = ["All"] + sorted(df["blade_spin"].dropna().unique().tolist())
    sel_spin = st.selectbox("Blade Spin", spins)

    min_placements = st.number_input("Min Placements", min_value=0, value=0, step=1)

# ---------------------------------------------------------------------------
# Apply filters
# ---------------------------------------------------------------------------
filtered = df[df["season"] == sel_season].copy()
if sel_type != "All":
    filtered = filtered[filtered["blade_type"] == sel_type]
if sel_spin != "All":
    filtered = filtered[filtered["blade_spin"] == sel_spin]
if min_placements > 0:
    filtered = filtered[filtered["total_placements"] >= min_placements]

st.markdown(f"**{len(filtered)}** combos — Season: **{sel_season}**")

# ---------------------------------------------------------------------------
# Leaderboard table
# ---------------------------------------------------------------------------
display = filtered[[
    "rank", "blade", "ratchet", "bit", "blade_type",
    "score", "win_rate", "podium_rate", "total_placements",
]].copy()
display["win_rate"] = (display["win_rate"] * 100).round(1)
display["podium_rate"] = (display["podium_rate"] * 100).round(1)
display.columns = ["Rank", "Blade", "Ratchet", "Bit", "Type",
                   "Score", "Win %", "Podium %", "Placements"]

st.dataframe(display, use_container_width=True, hide_index=True)

st.divider()

# ---------------------------------------------------------------------------
# Scatter: Win Rate vs Score
# ---------------------------------------------------------------------------
st.subheader("Win Rate vs Score")
if not filtered.empty:
    scatter_df = filtered.copy()
    scatter_df["win_pct"] = (scatter_df["win_rate"] * 100).round(1)

    fig = px.scatter(
        scatter_df,
        x="score",
        y="win_pct",
        color="blade_type",
        size="total_placements",
        hover_name="combo_key",
        hover_data={"blade": True, "ratchet": True, "bit": True, "score": True},
        labels={"score": "Score", "win_pct": "Win Rate (%)", "blade_type": "Blade Type"},
        color_discrete_sequence=px.colors.qualitative.Set1,
    )
    fig.update_layout(legend_title_text="Blade Type")
    st.plotly_chart(fig, use_container_width=True)
else:
    st.info("No data to chart with current filters.")

st.divider()

# ---------------------------------------------------------------------------
# Combo detail: season history for a selected combo
# ---------------------------------------------------------------------------
st.subheader("Combo Season History")
combo_options = ["—"] + filtered["combo_key"].tolist()
sel_combo = st.selectbox("Select a combo", combo_options)

if sel_combo != "—":
    history = df[df["combo_key"] == sel_combo].sort_values("season")
    hist_display = history[[
        "season", "rank", "score", "win_rate", "podium_rate", "total_placements"
    ]].copy()
    hist_display["win_rate"] = (hist_display["win_rate"] * 100).round(1)
    hist_display["podium_rate"] = (hist_display["podium_rate"] * 100).round(1)
    hist_display.columns = ["Season", "Rank", "Score", "Win %", "Podium %", "Placements"]
    st.dataframe(hist_display, use_container_width=True, hide_index=True)

    url_row = history.iloc[0]
    base_url = url_row["combo_url"].split("?")[0] if pd.notna(url_row["combo_url"]) else None
    if base_url:
        st.markdown(f"[View on BeybladeXMeta]({base_url})")
