# Generated by GitHub Copilot
"""
Combo Builder page: select individual parts and inspect the resulting combo's
stats and historical performance.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

import pandas as pd
import plotly.express as px
import streamlit as st
from sqlalchemy import text

from app.database import SessionLocal

st.title("⚙️ Combo Builder")
st.caption("Pick parts and explore the combo's stats and meta history")


@st.cache_resource
def get_session():
    """Return a shared SQLAlchemy session (cached across reruns)."""
    return SessionLocal()


db = get_session()


@st.cache_data(ttl=300)
def _combo_df():
    """Full combos + performance outer-join (cached)."""
    q = text("""
        SELECT
            c.combo_key, c.blade, c.assist_blade, c.ratchet, c.bit,
            c.blade_type, c.blade_spin,
            c.blade_weight_g, c.ratchet_weight_g, c.bit_weight_g, c.assist_weight_g,
            c.ratchet_gears, c.bit_height_mm, c.ratchet_burst_resistance,
            c.combo_url_base
        FROM combos c
        ORDER BY c.combo_key
    """)
    return pd.read_sql(q, db.bind)


@st.cache_data(ttl=300)
def _perf_df():
    q = text("SELECT combo_key, season, rank, score, win_rate, podium_rate, total_placements FROM combo_performance")
    return pd.read_sql(q, db.bind)


combos_df = _combo_df()
perf_df = _perf_df()

# ---------------------------------------------------------------------------
# Part option lists
# ---------------------------------------------------------------------------
blades = sorted(combos_df["blade"].dropna().unique().tolist())
ratchets = sorted(combos_df["ratchet"].dropna().unique().tolist())
bits = sorted(combos_df["bit"].dropna().unique().tolist())
assist_blades = ["None"] + sorted(
    [x for x in combos_df["assist_blade"].dropna().unique().tolist() if x != "None"]
)

# ---------------------------------------------------------------------------
# Part selectors
# ---------------------------------------------------------------------------
st.subheader("Select Parts")
col1, col2, col3, col4 = st.columns(4)
with col1:
    sel_blade = st.selectbox("Blade", blades)
with col2:
    sel_ratchet = st.selectbox("Ratchet", ratchets)
with col3:
    sel_bit = st.selectbox("Bit", bits)
with col4:
    sel_assist = st.selectbox("Assist Blade", assist_blades)

# ---------------------------------------------------------------------------
# Derived combo key (matches the pipe-delimited format used in the DB)
# ---------------------------------------------------------------------------
combo_key = f"{sel_blade}|{sel_assist}|{sel_ratchet}|{sel_bit}|None"

st.divider()

# ---------------------------------------------------------------------------
# Spec summary card
# ---------------------------------------------------------------------------
st.subheader("Combo Summary")

# Pull specs for the selected parts from the combos table (lookup by blade)
blade_row = combos_df[combos_df["blade"] == sel_blade]
ratchet_row = combos_df[combos_df["ratchet"] == sel_ratchet]
bit_row = combos_df[combos_df["bit"] == sel_bit]

blade_w = blade_row["blade_weight_g"].iloc[0] if not blade_row.empty else None
ratchet_w = ratchet_row["ratchet_weight_g"].iloc[0] if not ratchet_row.empty else None
bit_w = bit_row["bit_weight_g"].iloc[0] if not bit_row.empty else None

total_w = sum(v for v in [blade_w, ratchet_w, bit_w] if v is not None)

mc1, mc2, mc3, mc4 = st.columns(4)
mc1.metric("Blade Weight", f"{blade_w} g" if blade_w else "—")
mc2.metric("Ratchet Weight", f"{ratchet_w} g" if ratchet_w else "—")
mc3.metric("Bit Weight", f"{bit_w} g" if bit_w else "—")
mc4.metric("Est. Total Weight", f"{total_w:.1f} g" if total_w else "—")

blade_type = blade_row["blade_type"].iloc[0] if not blade_row.empty else "—"
blade_spin = blade_row["blade_spin"].iloc[0] if not blade_row.empty else "—"
ratchet_gears = ratchet_row["ratchet_gears"].iloc[0] if not ratchet_row.empty else "—"

sc1, sc2, sc3 = st.columns(3)
sc1.markdown(f"**Blade Type:** {blade_type}")
sc2.markdown(f"**Spin:** {blade_spin}")
sc3.markdown(f"**Ratchet Gears:** {ratchet_gears}")

st.divider()

# ---------------------------------------------------------------------------
# Performance history for the exact combo
# ---------------------------------------------------------------------------
st.subheader("Historical Performance")
exact_perf = perf_df[perf_df["combo_key"] == combo_key].sort_values("season")

if exact_perf.empty:
    st.info(f"No performance data for `{combo_key}` — this combo may not have appeared in tracked seasons, or the assist blade / lock chip differs.")
else:
    hist = exact_perf.copy()
    hist["win_rate"] = (hist["win_rate"] * 100).round(1)
    hist["podium_rate"] = (hist["podium_rate"] * 100).round(1)
    hist.columns = [c.replace("_", " ").title() for c in hist.columns]
    st.dataframe(hist, use_container_width=True, hide_index=True)

st.divider()

# ---------------------------------------------------------------------------
# Top combos sharing the selected blade / ratchet / bit
# ---------------------------------------------------------------------------
st.subheader(f"Top Combos Sharing Selected Parts")

tab_b, tab_r, tab_bi = st.tabs([f"Blade: {sel_blade}", f"Ratchet: {sel_ratchet}", f"Bit: {sel_bit}"])

_seasons = sorted(perf_df["season"].unique().tolist())
sel_s = st.selectbox("Season for top-combo lookup", _seasons, key="builder_season")

def _top_by_part(part_col: str, part_val: str) -> pd.DataFrame:
    """Return top 10 combos sharing a given part, for the selected season."""
    merged = combos_df.merge(
        perf_df[perf_df["season"] == sel_s],
        on="combo_key",
        how="inner",
    )
    top = (
        merged[merged[part_col] == part_val]
        .sort_values("score", ascending=False)
        .head(10)[["combo_key", "blade", "ratchet", "bit", "score", "win_rate", "total_placements"]]
        .copy()
    )
    top["win_rate"] = (top["win_rate"] * 100).round(1)
    top.columns = ["Combo Key", "Blade", "Ratchet", "Bit", "Score", "Win %", "Placements"]
    return top


with tab_b:
    st.dataframe(_top_by_part("blade", sel_blade), use_container_width=True, hide_index=True)
with tab_r:
    st.dataframe(_top_by_part("ratchet", sel_ratchet), use_container_width=True, hide_index=True)
with tab_bi:
    st.dataframe(_top_by_part("bit", sel_bit), use_container_width=True, hide_index=True)
