# Generated by GitHub Copilot
"""
ML Analysis page: train a win-rate prediction model and explore predictions.

Features:
- Train button triggers RandomForestRegressor on the selected season
- Feature importance bar chart
- Actual vs Predicted scatter plot
- Manual prediction input form
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

import numpy as np
import pandas as pd
import plotly.express as px
import streamlit as st

from ml.features import available_seasons, load_features
from ml.train import _DEFAULT_OUTPUT, train

st.title("🤖 ML Analysis")
st.caption("Win-rate prediction using RandomForest regression")

# ---------------------------------------------------------------------------
# Season selection
# ---------------------------------------------------------------------------
try:
    seasons = available_seasons()
except Exception as e:
    st.error(f"Could not load seasons from database: {e}")
    st.stop()

if not seasons:
    st.warning("Database is empty. Run `python app/seed.py` first.")
    st.stop()

sel_season = st.selectbox("Training Season", seasons)

# ---------------------------------------------------------------------------
# Train button
# ---------------------------------------------------------------------------
st.subheader("1. Train Model")

col_train, col_info = st.columns([1, 3])

with col_train:
    train_btn = st.button("🚀 Train Now", use_container_width=True)

with col_info:
    st.caption(
        "Trains a RandomForest regressor (200 trees) to predict **win_rate** from: "
        "blade weight, ratchet weight, bit weight, ratchet gears, bit height, "
        "blade type, bit type, blade spin, and ratchet burst resistance."
    )

if train_btn:
    with st.spinner("Training …"):
        try:
            metrics = train(season=sel_season)
            st.session_state["ml_metrics"] = metrics
            st.session_state["ml_season"] = sel_season
            st.success(
                f"Model trained! RMSE: {metrics['rmse']:.4f} | R²: {metrics['r2']:.4f} | "
                f"Train rows: {metrics['n_train']} | Test rows: {metrics['n_test']}"
            )
        except Exception as e:
            st.error(f"Training failed: {e}")

# Load model if it exists on disk (persists across page reruns)
model_bundle = None
if _DEFAULT_OUTPUT.exists():
    import joblib
    model_bundle = joblib.load(_DEFAULT_OUTPUT)

st.divider()

# ---------------------------------------------------------------------------
# Feature importance
# ---------------------------------------------------------------------------
st.subheader("2. Feature Importance")

if model_bundle is None:
    st.info("Train a model first to see feature importances.")
else:
    model = model_bundle["model"]
    feature_cols = model_bundle["feature_columns"]

    importance_df = pd.DataFrame({
        "Feature": feature_cols,
        "Importance": model.feature_importances_,
    }).sort_values("Importance", ascending=False)

    fig = px.bar(
        importance_df,
        x="Importance",
        y="Feature",
        orientation="h",
        color="Importance",
        color_continuous_scale="Blues",
        labels={"Importance": "Mean Decrease Impurity", "Feature": ""},
    )
    fig.update_layout(yaxis={"categoryorder": "total ascending"}, coloraxis_showscale=False)
    st.plotly_chart(fig, use_container_width=True)

st.divider()

# ---------------------------------------------------------------------------
# Actual vs Predicted scatter
# ---------------------------------------------------------------------------
st.subheader("3. Actual vs Predicted Win Rate")

if model_bundle is None:
    st.info("Train a model first to see predictions.")
else:
    try:
        X, y = load_features(season=model_bundle.get("season", sel_season))
        X_aligned = X.reindex(columns=model_bundle["feature_columns"], fill_value=0.0)
        y_pred = model_bundle["model"].predict(X_aligned)

        scatter_df = pd.DataFrame({
            "Actual Win Rate (%)": (y.values * 100),
            "Predicted Win Rate (%)": (y_pred * 100),
        })

        fig2 = px.scatter(
            scatter_df,
            x="Actual Win Rate (%)",
            y="Predicted Win Rate (%)",
            opacity=0.6,
            color_discrete_sequence=["#636EFA"],
        )
        # OLS trendline (computed via numpy — no statsmodels dependency)
        actual = scatter_df["Actual Win Rate (%)"].values
        predicted = scatter_df["Predicted Win Rate (%)"].values
        m, b = np.polyfit(actual, predicted, 1)
        x_line = np.array([actual.min(), actual.max()])
        fig2.add_scatter(
            x=x_line, y=m * x_line + b,
            mode="lines", name="Trend",
            line={"color": "#636EFA", "dash": "dot"},
        )
        # Perfect prediction reference line
        max_val = max(scatter_df.max().max(), 1)
        fig2.add_shape(
            type="line",
            x0=0, y0=0, x1=max_val, y1=max_val,
            line={"color": "red", "dash": "dash"},
        )
        fig2.update_layout(xaxis_title="Actual Win Rate (%)", yaxis_title="Predicted Win Rate (%)")
        st.plotly_chart(fig2, use_container_width=True)
    except Exception as e:
        st.warning(f"Could not generate predictions: {e}")

st.divider()

# ---------------------------------------------------------------------------
# Manual prediction form
# ---------------------------------------------------------------------------
st.subheader("4. Predict for a Custom Combo")

if model_bundle is None:
    st.info("Train a model first to enable predictions.")
else:
    with st.form("predict_form"):
        fc1, fc2, fc3 = st.columns(3)
        with fc1:
            blade_w = st.number_input("Blade Weight (g)", min_value=0.0, value=35.0, step=0.5)
            ratchet_w = st.number_input("Ratchet Weight (g)", min_value=0.0, value=6.0, step=0.5)
        with fc2:
            bit_w = st.number_input("Bit Weight (g)", min_value=0.0, value=3.0, step=0.5)
            ratchet_gears = st.number_input("Ratchet Gears", min_value=0, value=0, step=1)
        with fc3:
            bit_height = st.number_input("Bit Height (mm)", min_value=0.0, value=0.0, step=0.5)

        cf1, cf2, cf3, cf4 = st.columns(4)
        blade_type = cf1.selectbox("Blade Type", ["Attack", "Defense", "Stamina", "Balance"])
        bit_type = cf2.selectbox("Bit Type", ["Attack", "Defense", "Stamina", "Balance"])
        blade_spin = cf3.selectbox("Blade Spin", ["Right", "Left"])
        burst_res = cf4.selectbox("Burst Resistance", ["", "High", "Low"])

        submitted = st.form_submit_button("Predict Win Rate")

    if submitted:
        try:
            # Build a feature dict matching one-hot columns
            raw = {
                "blade_weight_g": blade_w,
                "ratchet_weight_g": ratchet_w,
                "bit_weight_g": bit_w,
                "ratchet_gears": float(ratchet_gears),
                "bit_height_mm": bit_height,
            }
            # One-hot encode to match training columns
            for col in model_bundle["feature_columns"]:
                if col not in raw:
                    raw[col] = 0.0

            raw[f"blade_type_{blade_type}"] = 1.0
            raw[f"bit_type_{bit_type}"] = 1.0
            raw[f"blade_spin_{blade_spin}"] = 1.0
            if burst_res:
                raw[f"ratchet_burst_resistance_{burst_res}"] = 1.0

            input_df = pd.DataFrame([raw]).reindex(columns=model_bundle["feature_columns"], fill_value=0.0)
            prediction = model_bundle["model"].predict(input_df)[0]

            st.success(f"**Predicted Win Rate: {prediction * 100:.1f}%**")
        except Exception as e:
            st.error(f"Prediction failed: {e}")
